# ---
# title: "CODEN_R_2"
# output: html_document
# ---
#
# ```{r setup, include=FALSE}
# knitr::opts_chunk$set(echo = TRUE)
# ```

# Setup and Import Libraries

options(scipen = 999)

library(lme4)
library(merTools)
library(lmerTest)
library(sjstats)
library(car)
library(emmeans)
library(dplyr)
library(ggplot2)
library(interactions)
library(MuMIn)
library(assertive.types)
library(sjPlot)
library(Hmisc)
library(corrplot)
library(rcompanion)
library(maptools)
library(rgdal)
library(spdep)
library(ctv)
library(tmap)
library(sf)
library(ape)
library(ggplot2)
library(deldir)
library(spatialreg)
library(jtools)

###Import the geodatabase feature class with cases removed in ArcMap
fgdb <- "CODEN_Project_Folder/FinalDataset.gdb"

subset(ogrDrivers(), grepl("GDB", name))
fc_list <- ogrListLayers(fgdb)
print(fc_list)
fc_C <- readOGR(dsn=fgdb,layer="FinalDataset_adj_na")
summary(fc_C)
plot(fc_C)

#Assign coordinates
coords_C<-coordinates(fc_C)

#Create the nb object with four neighbors
fc_kn4_C <- knn2nb(knearneigh(coords_C, k = 4))

#Make the nb object symmetrical (https://r-spatial.github.io/spdep/reference/testnb.html)
fc_kn4_C_s <- make.sym.nb(fc_kn4_C)

#Create the listw object from the nb object (fc_kn4) for four closest neighbors
fc_kn4_C_s_w <- nb2listw(fc_kn4_C_s, zero.policy = TRUE)

#First, declare variables as factors
fc_C$RE <- as.factor(fc_C$RE)
fc_C$Sex <- as.factor(fc_C$Sex)

##Run the ME model to calculate eigenvectors
model_splag_C <- ME(Hospitalized ~ AgeAtDx + Sex + RE + BMI + Tobacco + Diabetes + Hypertension + KidneyDisease + LungDisease, data = fc_C, family="binomial", listw=fc_kn4_C_s_w)

##Now calculate the model's coefficients
glm_model_splag_C <- glm(Hospitalized ~ AgeAtDx + Sex + RE + BMI + Tobacco + Diabetes + Hypertension + KidneyDisease + LungDisease + fitted(model_splag_C), data = fc_C, family="binomial")

##Run Summary
sink(file = "summary_indiv.txt")
summary(glm_model_splag_C)

sink(file = "exp_coef_indiv.txt")
exp(coef(glm_model_splag_C))

sink(file = "exp_confint_indiv.txt")
exp(confint(glm_model_splag_C))

sink(file = "nagelkerke_indiv.txt")
nagelkerke(glm_model_splag_C)

sink(file = "vif_indiv.txt")
vif(glm_model_splag_C)

sink(file = NULL)

#Final Save Point
save.image(file = "CODEN_DEM.RData")
